GET http://localhost:8000/
###
POST  http://localhost:8000/123/John

### read task api

GET http://localhost:8000/api/v1/task

###
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task":"coding",
    "hr":33,
     "type":"entry"
}
###
PATCH  http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id":"64850a6f89db696709eede7d",
    "type":"bad"
}

### delete
DELETE  http://localhost:8000/api/v1/task/648505d1ed33edba90616714
Content-Type: application/json
